name: Deploy to GitHub Pages

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout gh-pages
      uses: actions/checkout@gh-pages

    - name: Pulling master
      run: git pull origin/master

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "Pull from master" -a
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}